print('first change from git hub')
print('first change from local pc')
print('second change from git hub')
print('second change from local pc')
print ('third change from git hub')
print ('third change from local pc')
print('practice change from git hub')
print('practice change from local pc')
